### ISSUE TITLE
thay đổi biến

### ISSUE THREAD

**Issue by VUHAILAM** [AtulaDemon/RandomPrintWithAsio#4]
https://github.com/AtulaDemon/RandomPrintWithAsio/blob/53dde3358a374e27604b7220e5a00b580c1aac40/Printer.cpp#L18

cái này cho thành biến toàn cục private lúc khai báo class là chạy ok được, đã test thử :3

**Comment by AtulaDemon** [comment]
@VUHAILAM  t đã sửa được cái này rồi, muốn biết tại sao cơ :)))
