### ISSUE TITLE
thay đổi vị trí dòng lệnh

### ISSUE THREAD

**Issue by VUHAILAM** [AtulaDemon/RandomPrintWithAsio#5]
https://github.com/AtulaDemon/RandomPrintWithAsio/blob/e246219ad9ca73273e90b2ac922474e35183d04b/Printer.cpp#L29

dòng này thì m cho ở chỗ sinh số ấy, ở hàm printOneNumber() là fix được, không cho dừng ở chỗ chia việc

**Comment by AtulaDemon** [comment]
@VUHAILAM  cái này t cũng chữa được rồi, cần giải thích mà :v
